num_1 = input('Введите первое число: ')
asd = list(reversed(num_1))
qwe = ''.join(asd)
num_2 = input('Введите второе число: ')
ase = list(reversed(num_2))
zxc = ''.join(ase)
print(qwe)
print(zxc)
print(float(qwe) + float(zxc))
